// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS0FKfCsbASdMh0_Ecb_Iuce9OQ2zu-8c',
    appId: '1:188305800686:web:e9885064612b880d20e2ff',
    messagingSenderId: '188305800686',
    projectId: 'movies-club-8233e',
    authDomain: 'movies-club-8233e.firebaseapp.com',
    storageBucket: 'movies-club-8233e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZGUe0-mv5b335e-68297N5_pBP9qpRsk',
    appId: '1:188305800686:android:d5767274f78ca04b20e2ff',
    messagingSenderId: '188305800686',
    projectId: 'movies-club-8233e',
    storageBucket: 'movies-club-8233e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQZJWZGBtC0EcdMW-hejmqYoEyPAULf_M',
    appId: '1:188305800686:ios:803b294fc02a8c5e20e2ff',
    messagingSenderId: '188305800686',
    projectId: 'movies-club-8233e',
    storageBucket: 'movies-club-8233e.appspot.com',
    iosBundleId: 'com.example.moviesClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQZJWZGBtC0EcdMW-hejmqYoEyPAULf_M',
    appId: '1:188305800686:ios:c9a8685135e6ddcf20e2ff',
    messagingSenderId: '188305800686',
    projectId: 'movies-club-8233e',
    storageBucket: 'movies-club-8233e.appspot.com',
    iosBundleId: 'com.example.moviesClub.RunnerTests',
  );
}
